version: '3.8'

# Development override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - API_RELOAD=true
    volumes:
      # Mount source code for hot reload in development
      - ./app:/app/app
      - ./src:/app/src
      - ./.env:/app/.env:ro
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: builder  # Use builder stage for development
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_DEBUG=true
    volumes:
      # Mount source code for hot reload
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    ports:
      - "5173:5173"  # Vite dev server port